### ISSUE TITLE
please avoid use of non-portable on_exit()

### ISSUE THREAD

**Issue by kanavin** [rhboot/efivar#202] opened 2022-01-18 09:16 UTC
It is glibc-specifc, and this occurs on e.g. musl C library:
```
| /home/alex/development/poky/build-musl/tmp/work/core2-32-poky-linux-musl/efivar/38-r0/recipe-sysroot-native/usr/bin/i686-poky-linux-musl/../../libexec/i686-poky-linux-musl/gcc/i686-poky-linux-musl/11.2.0/ld.bfd: /home/alex/development/poky/build-musl/workspace/sources/efivar/src/efisecdb.c:382: undefined reference to `on_exit'
```

man on_exit says:

Portable application should avoid this function, and use the standard atexit(3) instead.

**Comment by oxr463** [comment] 2022-01-21 03:03
Duplicate of https://github.com/rhboot/efivar/issues/197

**Closed** 2022-04-18 17:05 UTC
Labels: good first issue
